[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
#remappings = ['forge-std/=lib/forge-std/src/', 'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/', 'ds-test/=lib/ds-test/src/']
rpc_endpoints = {mainnet = "https://rpc.ankr.com/eth", optimism = "https://rpc.ankr.com/optimism", fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum",celo = "https://rpc.ankr.com/celo",bsc = "https://rpc.ankr.com/bsc", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", Avalanche = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon"}
fs_permissions = [{ access = "read", path = "./"}]


[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
